[package]
name = "speculos-hid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
hidapi = "2.4.1"
uhid-virt = "0.0.6"
